/**
 * StaticBundleBackend — read-only filesystem for content shipped with the
 * package: API declarations (`/api/**`), examples (`/examples/**`), and
 * skill markdown (`/skills/**`).
 *
 * Content is provided as a path → content map at construction time.
 * In production, build tooling generates this map by walking the package's
 * `bundle/` directory. In tests, callers pass in a small fixture map.
 *
 * All write operations throw {@link SandboxReadOnlyError}.
 *
 * ```ts
 * // Production usage (typically generated by build):
 * import { apiBundle, examplesBundle, skillsBundle } from '@ablo/agent/bundles';
 *
 * const apiFs = new StaticBundleBackend({
 *   prefix: '/api',
 *   files: apiBundle,
 * });
 * ```
 */

import {
  SandboxNotFoundError,
  SandboxReadOnlyError,
  type Dirent,
  type GrepMatch,
  type SandboxStats,
} from '../interface';
import { globToRegex } from './glob-utils';
import type { VirtualFsBackend } from './types';

export interface StaticBundleBackendOptions {
  /** Path prefix this backend handles, e.g. `/api`. */
  prefix: string;
  /** Map of absolute path → file content. All paths must start with `prefix`. */
  files: Map<string, string> | Record<string, string>;
  /** Override the backend name shown in errors. Defaults to `static:<prefix>`. */
  name?: string;
}

export class StaticBundleBackend implements VirtualFsBackend {
  readonly name: string;
  readonly prefix: string;
  private readonly files: Map<string, string>;
  private readonly mtimeMs: number = Date.now();

  constructor(options: StaticBundleBackendOptions) {
    this.prefix = options.prefix;
    this.name = options.name ?? `static:${options.prefix}`;
    this.files =
      options.files instanceof Map
        ? options.files
        : new Map(Object.entries(options.files));

    // Validate every path falls under the prefix
    for (const path of this.files.keys()) {
      if (!path.startsWith(`${this.prefix}/`) && path !== this.prefix) {
        throw new Error(
          `StaticBundleBackend(${this.name}): file "${path}" is outside the prefix "${this.prefix}".`,
        );
      }
    }
  }

  matches(path: string): boolean {
    return path === this.prefix || path.startsWith(`${this.prefix}/`);
  }

  // ── Read operations ───────────────────────────────────────────────────

  async readFile(path: string): Promise<string> {
    const content = this.files.get(path);
    if (content === undefined) throw new SandboxNotFoundError(path);
    return content;
  }

  async stat(path: string): Promise<SandboxStats> {
    const content = this.files.get(path);
    if (content === undefined) throw new SandboxNotFoundError(path);
    return {
      isFile: () => true,
      isDirectory: () => false,
      size: content.length,
      mtimeMs: this.mtimeMs,
    };
  }

  async access(path: string): Promise<void> {
    if (!this.files.has(path)) throw new SandboxNotFoundError(path);
  }

  async mkdir(path: string): Promise<void> {
    // Static bundle is read-only — mkdir on a "real" path is rejected,
    // but for paths inside the prefix we no-op (compatible with agents
    // that call mkdir defensively before write attempts that will fail).
    throw new SandboxReadOnlyError(path);
  }

  async readdir(path: string): Promise<Dirent[]> {
    const dirPrefix = path.endsWith('/') ? path : `${path}/`;
    const fileNames = new Set<string>();
    const dirNames = new Set<string>();

    for (const filePath of this.files.keys()) {
      if (!filePath.startsWith(dirPrefix)) continue;
      const remainder = filePath.slice(dirPrefix.length);
      const slashIdx = remainder.indexOf('/');
      if (slashIdx === -1) {
        fileNames.add(remainder);
      } else {
        dirNames.add(remainder.slice(0, slashIdx));
      }
    }

    const entries: Dirent[] = [];
    for (const name of fileNames) {
      entries.push({
        name,
        isFile: () => true,
        isDirectory: () => false,
      });
    }
    for (const name of dirNames) {
      entries.push({
        name,
        isFile: () => false,
        isDirectory: () => true,
      });
    }
    return entries;
  }

  async glob(pattern: string): Promise<string[]> {
    const re = globToRegex(pattern);
    return [...this.files.keys()].filter((p) => re.test(p));
  }

  async grep(
    pattern: string,
    options?: { path?: string; caseInsensitive?: boolean },
  ): Promise<GrepMatch[]> {
    const re = new RegExp(pattern, options?.caseInsensitive ? 'i' : '');
    const out: GrepMatch[] = [];
    for (const [path, content] of this.files.entries()) {
      if (options?.path && !path.startsWith(options.path)) continue;
      const lines = content.split('\n');
      for (let i = 0; i < lines.length; i++) {
        if (re.test(lines[i])) {
          out.push({ path, lineNumber: i + 1, line: lines[i] });
        }
      }
    }
    return out;
  }

  // ── Write operations (all reject) ─────────────────────────────────────

  async writeFile(path: string): Promise<void> {
    throw new SandboxReadOnlyError(path);
  }

  async edit(path: string): Promise<void> {
    throw new SandboxReadOnlyError(path);
  }
}
