/**
 * Pure renderers for the error reference, shared by the generator
 * (generate-error-docs.mts, writes to disk) and the drift guard
 * (check-error-docs.mts, compares against disk). Keeping them pure — string
 * in, string out — is what lets the check prove the committed docs match the
 * registry without side effects.
 */
import {
  ERROR_CODES,
  ERROR_CONTRACT_VERSION,
  type ErrorCategory,
  type ErrorCodeSpec,
} from '../src/errorCodes.js';

const docUrlForCode = (code: string): string => `https://docs.abloatai.com/errors#${code}`;

const CATEGORY_ORDER: ReadonlyArray<{ key: ErrorCategory; title: string; blurb: string }> = [
  { key: 'auth', title: 'Authentication', blurb: 'Missing, invalid, revoked, or expired credentials. Re-authenticate.' },
  { key: 'permission', title: 'Permission', blurb: 'Credentials were valid but the action is forbidden for this caller.' },
  { key: 'capability', title: 'Capability', blurb: "The connection's resolved scope does not cover the attempted action." },
  { key: 'claim', title: 'Claim & intent contention', blurb: 'The target is held by another participant. Usually retryable once the holder releases.' },
  { key: 'conflict', title: 'Conflict', blurb: 'The write collided with concurrent state (stale read, idempotency mismatch, incompatible change).' },
  { key: 'validation', title: 'Validation', blurb: 'The request payload or parameters were invalid. Fix the input and retry.' },
  { key: 'not_found', title: 'Not found', blurb: 'The referenced resource does not exist (or is hidden by scope).' },
  { key: 'tenant', title: 'Tenant / schema resolution', blurb: 'The named model could not be resolved in the tenant schema.' },
  { key: 'schema', title: 'Schema', blurb: 'Schema declaration or migration problems.' },
  { key: 'intent', title: 'Intent lease', blurb: 'Intent-lease acquisition, queueing, and coordination.' },
  { key: 'bootstrap', title: 'Bootstrap', blurb: 'Initial snapshot fetch problems.' },
  { key: 'transport', title: 'Transport', blurb: 'Network, connection, queue, and timeout failures. Generally retryable.' },
  { key: 'rate_limit', title: 'Rate limit', blurb: 'Too many requests. Back off before retrying.' },
  { key: 'server', title: 'Server', blurb: 'Server-side failures. Generally retryable with backoff.' },
  { key: 'client', title: 'Client (SDK) invariants', blurb: 'Local SDK usage errors — never sent over the network. No HTTP status.' },
];

type Entry = { code: string; spec: ErrorCodeSpec };

function groupByCategory(): Map<ErrorCategory, Entry[]> {
  const byCategory = new Map<ErrorCategory, Entry[]>();
  for (const [code, spec] of Object.entries(ERROR_CODES) as [string, ErrorCodeSpec][]) {
    const list = byCategory.get(spec.category) ?? [];
    list.push({ code, spec });
    byCategory.set(spec.category, list);
  }
  for (const list of byCategory.values()) list.sort((a, b) => a.code.localeCompare(b.code));
  return byCategory;
}

export function renderErrorsMdx(): string {
  const byCategory = groupByCategory();
  const lines: string[] = [];
  lines.push('---');
  lines.push('title: "Error codes"');
  lines.push(
    'description: "Every error Ablo returns, by category. This page is generated from the canonical registry — its anchors are the target of each error\'s doc_url."',
  );
  lines.push('---');
  lines.push('');
  lines.push('{/* GENERATED by packages/sync-engine/scripts/generate-error-docs.mts — do not edit by hand. */}');
  lines.push('');
  lines.push(`Error contract version: \`${ERROR_CONTRACT_VERSION}\` (also sent on the \`Ablo-Version\` response header).`);
  lines.push('');
  lines.push('Every error — over HTTP or WebSocket — carries the same envelope:');
  lines.push('');
  lines.push('```json');
  lines.push(JSON.stringify(
    { type: 'AbloValidationError', code: 'invalid_body', message: 'The request body was missing, unparseable, or the wrong shape.', doc_url: 'https://docs.abloatai.com/errors#invalid_body', request_id: 'req_8f3a…' },
    null,
    2,
  ));
  lines.push('```');
  lines.push('');
  lines.push('`type` is the coarse class (catch with `instanceof`, or switch on it); `code` is the stable machine identifier documented below; `request_id` correlates to your server logs. Some errors carry extra structured fields (e.g. a schema push adds `warnings`).');
  lines.push('');
  lines.push('<Info>`retryable` indicates whether the *same* request can succeed on a later attempt without changing anything — transient transport/lease failures are retryable; validation and permission errors are not.</Info>');
  lines.push('');

  for (const { key, title, blurb } of CATEGORY_ORDER) {
    const entries = byCategory.get(key);
    if (!entries || entries.length === 0) continue;
    lines.push(`## ${title}`);
    lines.push('');
    lines.push(blurb);
    lines.push('');
    for (const { code, spec } of entries) {
      lines.push(`### ${code}`);
      lines.push('');
      lines.push(
        spec.surface === 'wire'
          ? `\`HTTP ${spec.httpStatus}\` · ${spec.retryable ? 'retryable' : 'not retryable'}`
          : '`client-only` · not sent over the network',
      );
      lines.push('');
      lines.push(spec.message);
      lines.push('');
    }
  }
  return lines.join('\n');
}

export function renderErrorsJson(): string {
  const spec = {
    $generated: 'packages/sync-engine/scripts/generate-error-docs.mts',
    version: ERROR_CONTRACT_VERSION,
    envelope: ['type', 'code', 'message', 'doc_url', 'request_id'],
    codes: (Object.entries(ERROR_CODES) as [string, ErrorCodeSpec][])
      .map(([code, s]) => ({
        code,
        category: s.category,
        surface: s.surface,
        ...(s.httpStatus !== undefined ? { httpStatus: s.httpStatus } : {}),
        retryable: s.retryable,
        message: s.message,
        docUrl: docUrlForCode(code),
      }))
      .sort((a, b) => a.code.localeCompare(b.code)),
  };
  return JSON.stringify(spec, null, 2) + '\n';
}

export function wireCodeCount(): number {
  return (Object.values(ERROR_CODES) as ErrorCodeSpec[]).filter((s) => s.surface === 'wire').length;
}

export function totalCodeCount(): number {
  return Object.keys(ERROR_CODES).length;
}
