/**
 * Generates TypeScript types from a serialized schema. Given the schema, it produces
 * the source text of a `.ts` module containing one row interface per model plus an
 * `AbloSchema` map, so an app is typed against the same schema the database and sync
 * layer enforce. This function is pure and returns the source as a string; the
 * command-line tool writes it to disk.
 *
 * It is the counterpart to the migration planner in {@link diffSchema}: you write one
 * schema definition, push it (which migrates the database), and generate types from
 * that same schema, so the types you code against, the rows the database stores, and
 * the entities the sync layer moves all describe the same thing.
 *
 * The generated interface covers the base columns plus each declared field, with
 * enums emitted as string-literal unions. Relations are not expanded here — the
 * runtime SDK resolves those through its typed accessors.
 */

import type { FieldMeta } from '../transaction/schema/field.js';
import { BASE_FIELDS } from '../transaction/schema/schema.js';
import type { SchemaJSON, ModelJSON } from './serialize.js';

function tsType(meta: FieldMeta): string {
  switch (meta.type) {
    case 'string':
      return 'string';
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'date':
      // `baseFieldsSchema` uses `z.date()` and the driver hydrates timestamptz
      // to Date — declared date fields match.
      return 'Date';
    case 'json':
      return 'unknown';
    case 'enum':
      return meta.enumValues && meta.enumValues.length > 0
        ? meta.enumValues.map((v) => `'${v.replace(/'/g, "\\'")}'`).join(' | ')
        : 'string';
    default:
      return 'unknown';
  }
}

/** A valid PascalCase TS identifier from a model's typename (or its key). */
function interfaceName(model: ModelJSON, key: string): string {
  const raw = model.typename && model.typename.trim() ? model.typename : key;
  const id = raw
    .replace(/[^A-Za-z0-9]+/g, ' ')
    .trim()
    .split(/\s+/)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('');
  return /^[A-Za-z_]/.test(id) ? id : `Model${id}`;
}

/** Emit a TypeScript module of row interfaces + the `AbloSchema` map. */
export function generateTypes(schema: SchemaJSON): string {
  const lines: string[] = [
    '// Generated by `ablo generate` — do not edit by hand.',
    '// Re-run `ablo generate` after pushing a schema change.',
    '',
  ];

  const nameByKey = new Map<string, string>();
  for (const [key, model] of Object.entries(schema.models)) {
    nameByKey.set(key, interfaceName(model, key));
  }

  for (const [key, model] of Object.entries(schema.models)) {
    lines.push(`export interface ${nameByKey.get(key)!} {`);
    lines.push('  id: string;');
    lines.push('  createdAt: Date;');
    lines.push('  updatedAt: Date;');
    lines.push('  organizationId?: string;');
    lines.push('  createdBy?: string;');
    for (const [fieldName, meta] of Object.entries(model.fields)) {
      // A model that redeclares a base column doesn't double-emit it.
      if ((BASE_FIELDS as readonly string[]).includes(fieldName)) continue;
      lines.push(`  ${fieldName}${meta.isOptional ? '?' : ''}: ${tsType(meta)};`);
    }
    lines.push('}');
    lines.push('');
  }

  // The model map — parameterize the Ablo client with this for typed access.
  lines.push('export interface AbloSchema {');
  for (const key of Object.keys(schema.models)) {
    lines.push(`  ${JSON.stringify(key)}: ${nameByKey.get(key)!};`);
  }
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}
