/**
 * Schema → TypeScript type emission — the `generate` half of the loop (the
 * counterpart to `diff`/migrate). Lowers a serialized schema to a `.ts` file of
 * row interfaces + an `AbloSchema` map, so a consumer's app is typed against the
 * exact schema that the database and sync layer enforce. Pure (returns source
 * text); the CLI writes it to disk.
 *
 * This is the SDK's front door: the developer writes ONE `defineSchema`, pushes
 * it (which migrates the DB), and generates types FROM the same schema — so the
 * types they code against, the rows the DB stores, and the entities sync moves
 * are provably the same thing.
 *
 * v1 emits the row shape (base columns + declared fields, enums as literal
 * unions). Relations are resolved by the runtime SDK's typed accessors and are
 * not expanded here.
 */

import type { FieldMeta } from './field.js';
import type { SchemaJSON, ModelJSON } from './serialize.js';

/** The base columns every model carries (mirrors `baseFieldsSchema`). */
const BASE_FIELDS = ['id', 'createdAt', 'updatedAt', 'organizationId', 'createdBy'] as const;

function tsType(meta: FieldMeta): string {
  switch (meta.type) {
    case 'string':
      return 'string';
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'date':
      // `baseFieldsSchema` uses `z.date()` and the driver hydrates timestamptz
      // to Date — declared date fields match.
      return 'Date';
    case 'json':
      return 'unknown';
    case 'enum':
      return meta.enumValues && meta.enumValues.length > 0
        ? meta.enumValues.map((v) => `'${v.replace(/'/g, "\\'")}'`).join(' | ')
        : 'string';
    default:
      return 'unknown';
  }
}

/** A valid PascalCase TS identifier from a model's typename (or its key). */
function interfaceName(model: ModelJSON, key: string): string {
  const raw = model.typename && model.typename.trim() ? model.typename : key;
  const id = raw
    .replace(/[^A-Za-z0-9]+/g, ' ')
    .trim()
    .split(/\s+/)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('');
  return /^[A-Za-z_]/.test(id) ? id : `Model${id}`;
}

/** Emit a TypeScript module of row interfaces + the `AbloSchema` map. */
export function generateTypes(schema: SchemaJSON): string {
  const lines: string[] = [
    '// Generated by `ablo generate` — do not edit by hand.',
    '// Re-run `ablo generate` after pushing a schema change.',
    '',
  ];

  const nameByKey = new Map<string, string>();
  for (const [key, model] of Object.entries(schema.models)) {
    nameByKey.set(key, interfaceName(model, key));
  }

  for (const [key, model] of Object.entries(schema.models)) {
    lines.push(`export interface ${nameByKey.get(key)!} {`);
    lines.push('  id: string;');
    lines.push('  createdAt: Date;');
    lines.push('  updatedAt: Date;');
    lines.push('  organizationId?: string;');
    lines.push('  createdBy?: string;');
    for (const [fieldName, meta] of Object.entries(model.fields)) {
      // A model that redeclares a base column doesn't double-emit it.
      if ((BASE_FIELDS as readonly string[]).includes(fieldName)) continue;
      lines.push(`  ${fieldName}${meta.isOptional ? '?' : ''}: ${tsType(meta)};`);
    }
    lines.push('}');
    lines.push('');
  }

  // The model map — parameterize the Ablo client with this for typed access.
  lines.push('export interface AbloSchema {');
  for (const key of Object.keys(schema.models)) {
    lines.push(`  ${JSON.stringify(key)}: ${nameByKey.get(key)!};`);
  }
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}
